variable "aws_region" {
  description = "AWS region to deploy resources in."
  type        = string
  default     = "us-east-1"
}

variable "project_name" {
  description = "Project name prefix for resources."
  type        = string
  default     = "microdemo"
}

variable "vpc_cidr" {
  description = "CIDR block for the VPC."
  type        = string
  default     = "10.0.0.0/16"
}

variable "public_subnet_cidr" {
  description = "CIDR block for the public subnet."
  type        = string
  default     = "10.0.1.0/24"
}

variable "s3_bucket_name" {
  description = "Name for the S3 bucket (optional, autogenerated if not set)."
  type        = string
  default     = null
}

variable "sqs_queue_name" {
  description = "Name for the SQS queue (optional, autogenerated if not set)."
  type        = string
  default     = null
}
